Create chaingpt-research.md
ubiquity/research pull request #140
Opened 2024-03-04 02:24 UTC by sergfeldman

Resolves #139

2024-03-04 09:45 UTC, pavlovcik requested changes
This overview is nice but is not ready because it lacks the second half of the prompt: 

> Make a plan and then we can replicate it in the form of GitHub tasks under a new repo.

2024-03-04 21:55 UTC, sergfeldman commented
@pavlovcik I will be very happy if we can achieve such success as ChainGPT. I have added a preliminary plan from my point of view.

2024-03-05 06:31 UTC, pavlovcik commented on chaingpt-research.md
> +To think that for such success as ChainGPT, we need to focus on a hype-able product, and not necessarily on serious development.
Well I think that we spent a fair amount of time developing the fundamentals of our business. Now we can embellish the truth and "sell the dream" which is common in sales and marketing.

Think of something like WeWork. They had a real business (albeit not profitable as far as I recall) but Adam Neumann made the idea of coworking spaces sound like something a lot more exciting than office spaces.

2024-03-05 06:32 UTC, pavlovcik reviewed
It seems like a lot of this is bottlenecked by me reviewing. Instead this task was intended for the researcher to provide proposals. I would review the proposals, not the raw research.

2024-03-05 23:34 UTC, sergfeldman commented
> It seems like a lot of this is bottlenecked by me reviewing. Instead this task was intended for the researcher to provide proposals. I would review the proposals, not the raw research.

I understand your request to receive a ready-made list of proposals as a result of research.
I think that this will not bring a positive result, because it is not incremental specific actions that are important, but the company strategy as a whole.
To understand the ChainGPT strategy, we need to dive a little deeper into it.

However, I have added key actions that I think are relevant to us.
Please let me know if you want anything else.

2024-03-06 01:06 UTC, pavlovcik commented
> I think that this will not bring a positive result, because it is not incremental specific actions that are important, but the company strategy as a whole.

I don't understand what you mean. Also, wouldn't it have made more sense to say this on the issue before starting the project if you think it doesn't make sense?

2024-03-06 18:13 UTC, sergfeldman commented
@pavlovcik My thoughts on comparing the approaches of Ubiquity and ChainGPT.
Ubiquity has a more rational and substantial approach, and ChainGPT is perceived as more innovative and emotional.
Certain actions make sense only in the context of a specific approach.

A few examples:

ChainGPT was accelerated by Seedify and this step is crucial for their growth.
Ubiquity did not go through acceleration.
It would be possible to add the task “Complete acceleration in Seedify” to the actionable plan.

The founder of ChainGPT is public and actively establishes partnerships. 
It would be possible to add the task “The founder should go public and actively establish partnerships.”

But I don't think it makes sense for Ubiquity to repeat these specific actions, because we have a different approach.
The top 5 recommendations that are relevant to us were added in the commit https://github.com/ubiquity/research/pull/140/commits/d7dfe1ed5a2e28c9e51755c1eac00ac38d741d44

2024-03-07 08:07 UTC, 0x4007 commented
> @pavlovcik My thoughts on comparing the approaches of Ubiquity and ChainGPT. Ubiquity has a more rational and substantial approach, and ChainGPT is perceived as more innovative and emotional. Certain actions make sense only in the context of a specific approach.

The purpose of this is to translate what they did into the context of what we are doing. 

> 
> A few examples:
> 
> ChainGPT was accelerated by Seedify and this step is crucial for their growth. Ubiquity did not go through acceleration. It would be possible to add the task “Complete acceleration in Seedify” to the actionable plan.

No but instead it would be "Complete acceleration with GitHub" for example. 


> The founder of ChainGPT is public and actively establishes partnerships. It would be possible to add the task “The founder should go public and actively establish partnerships.”

This should be a list of who we should establish partnerships with, based on what ChainGPT did. Besides, during fundraising we will be getting the team out there to meet with people so executing this is feasible. 

> But I don't think it makes sense for Ubiquity to repeat these specific actions, because we have a different approach. The top 5 recommendations that are relevant to us were added in the commit [d7dfe1e](https://github.com/ubiquity/research/commit/d7dfe1ed5a2e28c9e51755c1eac00ac38d741d44)

Those aren't actionable plans. I left comments.

2024-03-11 18:10 UTC, pavlovcik commented on chaingpt-research.md
> +https://coinband.io/case/chaingpt
Epic. Thanks for finding this.

2024-03-11 18:11 UTC, pavlovcik commented on chaingpt-research.md
> +https://medium.com/@chaingpt/chaingpt-pad-2023-a-year-of-unprecedented-success-in-web3-11e7db93615c
Interesting but I'm a bit skeptical. I need to spend more time reading through these carefully. Are there any salient points you want to point out for me?

2024-03-11 18:30 UTC, pavlovcik approved these changes
Great writeup!

2024-03-11 18:30 UTC, pavlovcik commented on chaingpt-research.md
> +Alex: will do when producing Series A fundraising materials.
I need to spend more time copying (for a lack of better term) what other crypto AI startups say. You put together some interesting narratives of the other projects in another thread somewhere. When I catch more time to work on the pitchdeck, I'll spend a lot of time studying the other narratives. 

Please feel free to follow along on the pitchdeck progress at https://github.com/ubiquity/series-a/issues/13

Please feel free to leave comments, or fork a copy (don't edit in place!) if you're inspired to edit the deck.

2024-03-11 18:30 UTC, pavlovcik commented on chaingpt-research.md
> +https://www.producthunt.com/products/chaingpt/reviews
This is funny to me that they went on producthunt. I assume these are fake reviews, but honestly it doesn't even matter for the purposes of marketing.

2024-03-11 18:30 UTC, pavlovcik commented on chaingpt-research.md
> +>We carefully selected over 47 influencers who were given a four-week timeframe to promote the project and the upcoming IDO. These influencers helped us expand the project's community, resulting in o
I can have our lead generation guy do a campaign for this!

2024-03-11 18:30 UTC, pavlovcik commented on chaingpt-research.md
> +It doesn't make sense to collect lists of influencers because they usually interact with professional agencies, not companies.
I'm not sure that I agree. If we pay them I'm pretty certain they wouldn't care who's contacting them.

2024-03-11 18:30 UTC, pavlovcik commented on chaingpt-research.md
> +For small companies like Ubiquity, it is extremely costly and ineffective to collect and maintain a pool of influencers, so they usually collaborate with marketing agencies.
I would like to try.

2024-03-11 18:30 UTC, pavlovcik commented on chaingpt-research.md
> +An effective marketing agency can coordinate influencers and other communication channels into a single campaign that brings results.
This is probably true but I've never had a good experience with a marketing agency yet so if we choose one to work with, ideally it was the same that worked with ChainGPT etc. Basically proven talent.

2024-03-11 18:31 UTC, merged